name: clareza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-113.1.beta

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
